name: Build and Push Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: blogdb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt

      - name: Run user tests
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost/blogdb
        run: |
          . venv/bin/activate
          pytest tests/user_test.py --maxfail=1 --disable-warnings -q

      - name: Run post tests
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost/blogdb
        run: |
          . venv/bin/activate
          pytest tests/comment_test.py --maxfail=1 --disable-warnings -q
  build:
    needs: test  
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          
      - name: Build Docker image
        run: |
          docker build -t "${{ secrets.DOCKERHUB_USERNAME }}/back:latest" .
  
      - name: Push Docker image 
        run: docker push "${{ secrets.DOCKERHUB_USERNAME }}/back:latest"

  deploy:
    needs: build  
    runs-on: ubuntu-latest
  
    steps:
    
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GCLOUD_SSH_KEY }}" > ~/.ssh/gcloud_key
          chmod 600 ~/.ssh/gcloud_key
  
      - name: SSH into VM and deploy container
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/gcloud_key ${{ secrets.GCLOUD_USER }}@${{ secrets.GCLOUD_VPN_HOST }} "
            ssh -o StrictHostKeyChecking=no -i ~/.ssh/gcloud_key ${{ secrets.GCLOUD_USER }}@${{ secrets.GCLOUD_HOST }} '

              echo "SECRET_KEY=${{ secrets.FLASK_SECRET_KEY }}" >> .env
              echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
              echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET }}" >> .env

              echo "${{ secrets.DOCKERHUB_TOKEN }}" | sudo docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
              sudo docker stop back || true
              sudo docker rm back || true
              sudo docker image prune -f
              sudo docker pull "${{ secrets.DOCKERHUB_USERNAME }}"/back:latest
              sudo docker run --env-file .env -d --name back -p 5000:5000 "${{ secrets.DOCKERHUB_USERNAME }}"/back:latest
            '
          "
          
